"""test

Revision ID: 0edb7ca14d0d
Revises: 
Create Date: 2020-12-01 22:00:24.254071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edb7ca14d0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SysMenus',
    sa.Column('CreateUserid', sa.SmallInteger(), nullable=False),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyUserid', sa.SmallInteger(), nullable=False),
    sa.Column('Status', sa.SmallInteger(), nullable=True),
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ParentId', sa.SmallInteger(), nullable=False),
    sa.Column('MenuName', sa.String(length=50), nullable=False),
    sa.Column('MenuIcon', sa.String(length=50), nullable=True),
    sa.Column('MenuUrl', sa.String(length=100), nullable=True),
    sa.Column('MenuTarget', sa.String(length=50), nullable=True),
    sa.Column('MenuSort', sa.SmallInteger(), nullable=True),
    sa.Column('MenuType', sa.SmallInteger(), nullable=False),
    sa.Column('Authorize', sa.String(length=50), nullable=True),
    sa.Column('Remark', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('SysRoles',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CreateUserid', sa.SmallInteger(), nullable=False),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyUserid', sa.SmallInteger(), nullable=False),
    sa.Column('Status', sa.SmallInteger(), nullable=True),
    sa.Column('Name', sa.String(length=20), nullable=True),
    sa.Column('Sort', sa.SmallInteger(), nullable=True),
    sa.Column('Remark', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('SysUsers',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CreateUserid', sa.SmallInteger(), nullable=False),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyUserid', sa.SmallInteger(), nullable=False),
    sa.Column('Status', sa.SmallInteger(), nullable=True),
    sa.Column('UserName', sa.String(length=30), nullable=False),
    sa.Column('PassWord', sa.String(length=150), nullable=False),
    sa.Column('RealName', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('Mobile', sa.String(length=11), nullable=True),
    sa.Column('Gender', sa.SmallInteger(), nullable=True),
    sa.Column('Salt', sa.String(length=4), nullable=True),
    sa.Column('IsOnLine', sa.SmallInteger(), nullable=True),
    sa.Column('LastTime', sa.DateTime(), nullable=True),
    sa.Column('LastIp', sa.String(length=20), nullable=True),
    sa.Column('Portrait', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email')
    )
    op.create_index(op.f('ix_SysUsers_UserName'), 'SysUsers', ['UserName'], unique=True)
    op.create_table('entry',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CreateUserid', sa.SmallInteger(), nullable=False),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyUserid', sa.SmallInteger(), nullable=False),
    sa.Column('Status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('SysUserBelongs',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CreateUserid', sa.SmallInteger(), nullable=False),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyUserid', sa.SmallInteger(), nullable=False),
    sa.Column('Status', sa.SmallInteger(), nullable=True),
    sa.Column('Belongid', sa.SmallInteger(), nullable=False),
    sa.Column('BelongType', sa.SmallInteger(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('Remark', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['SysUsers.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SysUserBelongs')
    op.drop_table('entry')
    op.drop_index(op.f('ix_SysUsers_UserName'), table_name='SysUsers')
    op.drop_table('SysUsers')
    op.drop_table('SysRoles')
    op.drop_table('SysMenus')
    # ### end Alembic commands ###
