"""test

Revision ID: 3601d666c7f0
Revises: 4052e17d0c9e
Create Date: 2020-12-15 18:00:15.278044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3601d666c7f0'
down_revision = '4052e17d0c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SysUsers_ibfk_2', 'SysUsers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('SysUsers_ibfk_2', 'SysUsers', 'SysPosition', ['PositionId'], ['Id'])
    # ### end Alembic commands ###
