"""test

Revision ID: 3dddea4857cd
Revises: 
Create Date: 2020-11-05 22:29:10.349907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dddea4857cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sysRoles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sysUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('realname', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('salt', sa.String(length=4), nullable=True),
    sa.Column('isonline', sa.SmallInteger(), nullable=True),
    sa.Column('lasttime', sa.DateTime(), nullable=True),
    sa.Column('lastip', sa.String(length=20), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['sysRoles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sysUsers_email'), 'sysUsers', ['email'], unique=True)
    op.create_index(op.f('ix_sysUsers_username'), 'sysUsers', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sysUsers_username'), table_name='sysUsers')
    op.drop_index(op.f('ix_sysUsers_email'), table_name='sysUsers')
    op.drop_table('sysUsers')
    op.drop_table('sysRoles')
    # ### end Alembic commands ###
