"""test

Revision ID: 4052e17d0c9e
Revises: f1464b9eb615
Create Date: 2020-12-15 17:18:31.802069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4052e17d0c9e'
down_revision = 'f1464b9eb615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SysUsers', sa.Column('Remark', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'SysUsers', ['Remark'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SysUsers', type_='unique')
    op.drop_column('SysUsers', 'Remark')
    # ### end Alembic commands ###
