"""日志表

Revision ID: 4104edaaae6f
Revises: 
Create Date: 2020-12-23 14:04:15.321631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4104edaaae6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Remark', table_name='SysUsers2')
    op.drop_table('SysUsers2')
    op.drop_table('test')
    op.add_column('SysLog', sa.Column('Browser', sa.String(length=50), nullable=True, comment='浏览器'))
    op.add_column('SysLog', sa.Column('ExecuteParam', sa.String(length=500), nullable=True, comment='请求参数'))
    op.add_column('SysLog', sa.Column('ExecuteResult', sa.String(length=500), nullable=True, comment='请求结果'))
    op.add_column('SysLog', sa.Column('ExecuteTime', sa.Integer(), nullable=True, comment='执行时间'))
    op.add_column('SysLog', sa.Column('ExecuteUrl', sa.String(length=100), nullable=True, comment='页面地址'))
    op.add_column('SysLog', sa.Column('IpLocation', sa.String(length=50), nullable=True, comment='ip位置'))
    op.add_column('SysLog', sa.Column('LogType', sa.Integer(), nullable=True, comment='日志类型(暂未用到)'))
    op.add_column('SysLog', sa.Column('OS', sa.String(length=50), nullable=True, comment='操作系统'))
    op.drop_constraint('SysLog_ibfk_1', 'SysLog', type_='foreignkey')
    op.drop_column('SysLog', 'Parameter')
    op.drop_column('SysLog', 'UserId')
    op.drop_column('SysLog', 'LogCategory')
    op.drop_column('SysLog', 'TimeConsue')
    op.drop_column('SysLog', 'OperatingSystem')
    op.drop_column('SysLog', 'OperationMethod')
    op.drop_column('SysLog', 'OperatingInfo')
    op.drop_column('SysLog', 'AgentBrowser')
    op.drop_column('SysLog', 'IpHome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SysLog', sa.Column('IpHome', mysql.VARCHAR(length=60), nullable=True, comment='ip归属地'))
    op.add_column('SysLog', sa.Column('AgentBrowser', mysql.VARCHAR(length=200), nullable=True, comment='浏览器'))
    op.add_column('SysLog', sa.Column('OperatingInfo', mysql.VARCHAR(length=200), nullable=True, comment='操作信息'))
    op.add_column('SysLog', sa.Column('OperationMethod', mysql.VARCHAR(length=30), nullable=True, comment='操作方法'))
    op.add_column('SysLog', sa.Column('OperatingSystem', mysql.VARCHAR(length=60), nullable=True, comment='操作系统'))
    op.add_column('SysLog', sa.Column('TimeConsue', mysql.INTEGER(), autoincrement=False, nullable=True, comment='耗时'))
    op.add_column('SysLog', sa.Column('LogCategory', mysql.INTEGER(), autoincrement=False, nullable=True, comment='日志列表'))
    op.add_column('SysLog', sa.Column('UserId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('SysLog', sa.Column('Parameter', mysql.VARCHAR(length=200), nullable=True, comment='请求参数'))
    op.create_foreign_key('SysLog_ibfk_1', 'SysLog', 'SysUsers', ['UserId'], ['Id'])
    op.drop_column('SysLog', 'OS')
    op.drop_column('SysLog', 'LogType')
    op.drop_column('SysLog', 'IpLocation')
    op.drop_column('SysLog', 'ExecuteUrl')
    op.drop_column('SysLog', 'ExecuteTime')
    op.drop_column('SysLog', 'ExecuteResult')
    op.drop_column('SysLog', 'ExecuteParam')
    op.drop_column('SysLog', 'Browser')
    op.create_table('test',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Remark', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('SysUsers2',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Remark', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('Remark', 'SysUsers2', ['Remark'], unique=True)
    # ### end Alembic commands ###
