"""日志表

Revision ID: 5b3cd9f6c4b1
Revises: 4104edaaae6f
Create Date: 2020-12-23 14:11:51.843823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3cd9f6c4b1'
down_revision = '4104edaaae6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SysLog', sa.Column('Remark', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SysLog', 'Remark')
    # ### end Alembic commands ###
