"""test

Revision ID: 92cb54865623
Revises: ffa5b26d409b
Create Date: 2020-12-15 18:04:27.631169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cb54865623'
down_revision = 'ffa5b26d409b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SysUsers', sa.Column('PositionId', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SysUsers', 'PositionId')
    # ### end Alembic commands ###
