"""menu

Revision ID: b8281942f732
Revises: 5b3cd9f6c4b1
Create Date: 2020-12-31 18:42:01.846723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8281942f732'
down_revision = '5b3cd9f6c4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MenuAuthorize',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('CreateUserid', sa.SmallInteger(), nullable=False),
    sa.Column('CreateTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyTime', sa.DateTime(), nullable=True),
    sa.Column('ModifyUserid', sa.SmallInteger(), nullable=False),
    sa.Column('Status', sa.SmallInteger(), nullable=True),
    sa.Column('MenuId', sa.Integer(), nullable=True, comment='菜单Id'),
    sa.Column('AuthorizeId', sa.Integer(), nullable=True, comment='授权Id(角色Id或者用户Id)'),
    sa.Column('AuthorizeType', sa.Integer(), nullable=True, comment='授权类型(1角色 2用户)'),
    sa.Column('Remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MenuAuthorize')
    # ### end Alembic commands ###
