"""test

Revision ID: d81887a96382
Revises: 89fb699d0c98
Create Date: 2020-12-15 14:20:10.248629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd81887a96382'
down_revision = '89fb699d0c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SysPosition', 'PositionStatus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SysPosition', sa.Column('PositionStatus', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
