"""test

Revision ID: f1464b9eb615
Revises: 1185b77708b2
Create Date: 2020-12-15 16:54:01.580071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1464b9eb615'
down_revision = '1185b77708b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SysUsers', sa.Column('RoleId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SysUsers', 'SysRoles', ['RoleId'], ['Id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SysUsers', type_='foreignkey')
    op.drop_column('SysUsers', 'RoleId')
    # ### end Alembic commands ###
