"""test

Revision ID: ffa5b26d409b
Revises: 3601d666c7f0
Create Date: 2020-12-15 18:03:52.447326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffa5b26d409b'
down_revision = '3601d666c7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SysUsers', 'PositionId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SysUsers', sa.Column('PositionId', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
